name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/personal.pem << 'EOF'
        ${{ secrets.SSH_PRIVATE_KEY }}
        EOF
        chmod 600 ~/.ssh/personal.pem
        ssh-keyscan ec2-16-171-52-187.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/personal.pem ubuntu@ec2-16-171-52-187.eu-north-1.compute.amazonaws.com << 'EOF'
          cd ~/civic-pulse
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF